//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoRP.Modules.Vehicle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoRP.Modules.Vehicle.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Vehicle carregado!.
        /// </summary>
        internal static string console_startup {
            get {
                return ResourceManager.GetString("console_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este veículo já está spawnado!.
        /// </summary>
        internal static string vehicle_already_spawned {
            get {
                return ResourceManager.GetString("vehicle_already_spawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha uma ação válida!.
        /// </summary>
        internal static string vehicle_invalid_action {
            get {
                return ResourceManager.GetString("vehicle_invalid_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este veículo está trancado!.
        /// </summary>
        internal static string vehicle_locked {
            get {
                return ResourceManager.GetString("vehicle_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não possui as chaves deste veículo!.
        /// </summary>
        internal static string vehicle_no_keys {
            get {
                return ResourceManager.GetString("vehicle_no_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não está dirigindo um veículo!.
        /// </summary>
        internal static string vehicle_not_driving {
            get {
                return ResourceManager.GetString("vehicle_not_driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não está próximo de nenhum veículo!.
        /// </summary>
        internal static string vehicle_not_near_any {
            get {
                return ResourceManager.GetString("vehicle_not_near_any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este portamalas já está fechado!.
        /// </summary>
        internal static string vehicle_trunk_already_closed {
            get {
                return ResourceManager.GetString("vehicle_trunk_already_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este portamalas já está aberto!.
        /// </summary>
        internal static string vehicle_trunk_already_opened {
            get {
                return ResourceManager.GetString("vehicle_trunk_already_opened", resourceCulture);
            }
        }
    }
}
